### PR TITLE
Refactor

### LINKED ISSUE #1: Alternatives
Hi @mikesplain!

Thanks for your repo - it's exactly what I've just needed. Seeing that you haven't been working on this container though, I'm wondering if you are still using it after two years. Maybe there's a mainstream alternative for doing a simple redirect like your container, which I haven't found? Would be good if you shared your thoughts.

### PR DESCRIPTION
**Pull request by kachkaev**
- use alpine nginx
- remove client_max_body_size limit

Fixes #1

### CODE REVIEW

**Comment by kachkaev** [comment]
ping @mikesplain :–)

**Comment by iBobik** [comment]
Why not to fix only to major version (`FROM 1-alpine`)?

**Comment by iBobik** [comment]
@mikesplain Ping again after more than a year :-)

**Comment by iBobik** [comment]
After merge do not forget to configure repository link to "nginx" in [Build Settings](https://hub.docker.com/r/mikesplain/nginx-proxy-pass/~/settings/automated-builds/), so it will rebuild on Nginx updates automatically.

**Comment by mikesplain** [comment]
Thanks @kachkaev and @iBobik. Totally missed this somehow, merging now.

**Pull request merged**
